SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = .9  # seconds
POWERUP_SPAWN_RATE = 10 # seconds
POWERUP_SPEED = 150
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_MAX_SPEED = 2000
PLAYER_ACCELERATION = 300
DAMPING_FACTOR = .98
SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500
PLAYER_SINGLE_SHOOT_COOLDOWN = .3
PLAYER_TRIPLE_SHOOT_COOLDOWN = .5

START_MENU = 0
GAME = 1
GAME_OVER = 2